services:
  # Ollama service for LLM
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11436:11434"
    volumes:
      - ollama_data:/root/.ollama

  # RAGSST App
  ragsst-app:
      container_name: ragsst-app
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "7860:7860"
      volumes:
        - ./data:/app/data
        - ./vector_db:/app/vector_db
        - ./exports:/app/exports
        - ./log:/app/log
      environment:
        - OLLAMA_BASE_URL=http://ollama:11434/v1
      depends_on:
        - ollama
      restart: unless-stopped
      command: .venv/bin/python app.py

volumes:
  ollama_data: