version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    pull_policy: always
    tty: true
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  ragsst-app:
    build: .
    container_name: ragsst-app
    depends_on:
      - ollama
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./vector_db:/app/vector_db
      - ./exports:/app/exports
      - ./log:/app/log
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    entrypoint: ["python3", "app.py"]

volumes:
  ollama_data: 